import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Tiermaker",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className}
                    min-h-screen
                    bg-gradient-to-b
                    from-gray-100 to-gray-50 text-black
                    dark:from-gray-950 dark:to-gray-800 dark:text-white
                    bg-fixed bg-center bg-no-repeat
                `}
            >
                {children}
            </body>
        </html>
    );
}
